@startuml
actor Patient
participant FE as "Frontend"
participant MDR as "Microservice"

Patient -> FE : Asks to log in
FE -> Patient : Asks for login credentials
Patient -> FE : Sends login credentials (Email, Password)
FE -> MDR : Sends HTTP Request to log in with credentials
MDR -> MDR : Validates credentials
MDR -> FE : Returns login success/failure status
FE -> Patient : Returns login success/failure message
@enduml