@startuml level_2

title Level 2 Diagram

hide empty members

skinparam class {
    BackgroundColor<<valueObject>> #D6EAF8
    BackgroundColor<<root>> #FDEBD0
    BackgroundColor<<service>> #D1F2EB
    BackgroundColor #FEF9E7
    ArrowColor Black
}

skinparam package {
    BackgroundColor #EBF5FB
}

actor Doctor as D
participant "Operation Request FE" as FE
participant "Operation Request MDR" as MDR

activate D
D -> FE: Requests to create an operation request
activate FE
FE --> D: Asks for operation request details
deactivate FE
D -> FE: Sends operation request data (patientID, operationType, deadlineDate, priority)
activate FE
FE -> MDR: Sends HTTP Request to create an operation request with data
activate MDR
MDR -> MDR: Validates operation request data
MDR -> MDR: Creates operation request
MDR --> FE: Returns Operation Status Code
deactivate MDR
FE --> D: Returns Operation Request Success message
FE --> Patient: Notifies patient about the operation request
deactivate FE

@enduml