@startuml level_1

skinparam handwritten false
skinparam monochrome false
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing true

actor Backoffice_User as BOU

activate BOU
BOU -> System: Ask to login in the system
activate System
System -> BOU: Ask for user's data (email, password)
BOU -> System: Send user's data (email, password)
System -> System: Validate user's data
System -> BOU: Send confirmation message
deactivate System

@enduml