@startuml level_1

title Level 1 Diagram for US 7.2.7

hide empty members

skinparam class {
    BackgroundColor<<valueObject>> #D6EAF8
    BackgroundColor<<root>> #FDEBD0
    BackgroundColor<<service>> #D1F2EB
    BackgroundColor #FEF9E7
    ArrowColor Black
}

skinparam package {
    BackgroundColor #EBF5FB
}

actor Doctor as D

activate D
D -> System: Requests entries in the Patient Medical Record
activate System
System --> D: Displays Patients Medicals Records   
deactivate System
D -> System: Select Patient Medical Record to view
activate System
System -> System: Validates Patient Medical Record
System --> D: Returns results of Patient Medical Conditions and Allergies
deactivate System

@enduml