@startuml US5.1.1  Level 3
'https://plantuml.com/sequence-diagram
skinparam handwritten false
skinparam monochrome false
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing true

actor Admin as AD

activate AD
AD-> Routes: post(\data)
activate Routes
Routes -> MDR: createUser(data)
activate MDR
MDR -> Controller: createUser(data)
activate Controller
Controller -> Service: instance().createUser(data)
activate Service
Service -> CreatingUserDTO: createUser(data)
activate CreatingUserDTO
DTO -> Repository: saveBuilding(building)
activate Repository
Repository -> Repository: save()
Repository --> DTO: 200
deactivate Repository
DTO --> Service: 200
deactivate DTO
Service --> Controller: 200
deactivate Service
Controller --> MDR: 200
deactivate Controller
MDR --> Routes: 200
deactivate MDR
Routes --> USER: building created
deactivate Routes

@enduml
