@startuml level_2
'https://plantuml.com/sequence-diagram
skinparam handwritten false
skinparam monochrome false
skinparam packageStyle rect
skinparam shadowing true

title 5.1.21 Level 2 Diagra

actor ADMIN as AD
activate AD
AD -> UI: send request to edit operation type
activate UI
UI -> AD: ask to especify the ID and the new data of the operation type
AD -> UI: updateOperationType(ID, newOperationTypeData)
UI-> MDR: updateOperationType(ID, newOperationTypeData)
activate MDR
MDR --> MDR: Validate ID and newOperationTypeData
MDR --> UI: 200 (Success) OR 400 (Bad Request)
deactivate MDR
UI -> AD: 200 (Success) OR 400 (Bad Request)
deactivate AD

@enduml

