@startuml US 5.1.1 Level 1

skinparam handwritten false
skinparam monochrome false
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing true

actor Admin as AD

activate AD
AD -> System: Ask for create a user
activate System
System -> AD: Ask for user's data
AD -> System: Send user's data (username, email,role)
System -> System: Validate user's data
System -> AD: Send confirmation message
deactivate System

@enduml