@startuml level_2
'https://plantuml.com/sequence-diagram
skinparam handwritten false
skinparam monochrome false
skinparam packageStyle rect
skinparam shadowing true

title 5.1.23 Level 2 Diagram

actor ADMIN as AD
activate AD
AD -> UI: send request to list or search operation types
activate UI

alt List all operation types
    UI -> Controller: getAllOperationTypes()
    activate Controller
    Controller --> UI: operationTypeList OR 400 (Bad Request)
    deactivate Controller
    UI -> AD: operationTypeList OR 400 (Bad Request)

else Search for operation type
    AD -> UI: send operationTypeID or operationTypeName
    UI -> Controller: getOperationType(operationTypeID or operationTypeName)
    activate Controller
    Controller --> UI: operationTypeData OR 404 (Not Found)
    deactivate Controller
    UI -> AD: operationTypeData OR 404 (Not Found)
end

deactivate UI
deactivate AD

@enduml
