@startuml level_1
skinparam handwritten false
skinparam monochrome false
skinparam packageStyle rect
skinparam shadowing true
title 5.1.22 Level 1 Diagram

actor Admin as AD

activate AD
AD -> System: Ask to delete types of operations
activate System
System -> AD: Ask for type of operation data to delete(ID or name)
AD -> System: Send ID or name of type of operation to delete
System -> System: Validate ID or Name
System -> AD: Send confirmation message(Success or Failure)
deactivate System

@enduml