@startuml level_1

title Level 1 Diagram for Deactivating Staff

hide empty members
'skinparam Linetype ortho

skinparam class {
    BackgroundColor<<valueObject>> #D6EAF8
    BackgroundColor<<root>> #FDEBD0
    BackgroundColor<<service>> #D1F2EB
    BackgroundColor #FEF9E7
    ArrowColor Black
}

skinparam package {
    BackgroundColor #EBF5FB
}

actor Admin as A

activate A
A -> System: Asks to deactivate a Staff's Profile
activate System
System --> A: Asks for Staff's Id to deactivate
deactivate System
A -> System: Sends Staff's Id
activate System
System -> System: Validates the Staff's Id and deactivates the Staff's profile
System --> A: Returns Operation In/Success message
deactivate System

@enduml