@startuml level_2
'https://plantuml.com/sequence-diagram
skinparam handwritten false
skinparam monochrome false
skinparam packageStyle rect
skinparam shadowing true

title 5.1.22 Level 2 Diagra

actor ADMIN as AD
activate AD
AD -> UI: send request to delete operation type
activate UI
UI -> AD: ask to especify the ID or the name of the operation type
AD -> UI: deleteOperationType(ID/name)
UI-> MDR: deleteOperationType(ID/name)
activate MDR
MDR --> MDR: Validate ID or 
MDR --> UI: 200 (Success) OR 400 (Bad Request)
deactivate MDR
UI -> AD: 200 (Success) OR 400 (Bad Request)
deactivate AD

@enduml

