@startuml level_1

title Level 1 Diagram

hide empty members

actor Patient as P

activate P
P -> System: Requests to Update Profile
activate System
System --> P: Asks for data to update profile
deactivate System
P -> System: Sends data(name, email, phone number)
activate System
System -> System: Validates data and updates profile
System --> P: Returns Success/Error message
deactivate System

@enduml