@startuml level_2
'https://plantuml.com/sequence-diagram
skinparam handwritten false
skinparam monochrome false
skinparam packageStyle rect
skinparam shadowing true
title 5.1.20 Level 2 Diagram

actor ADMIN as AD
activate AD
AD -> UI: Create new types of operations (name, requiredStaffBySpecialization, estimatedDuration)
activate UI
UI-> MDR: createOperationType(name, requiredStaffBySpecialization, estimatedDuration)
activate MDR
MDR --> MDR: Validate operation type data
MDR --> UI: 200 (Success) OR 400 (Bad Request)
deactivate MDR
UI -> AD: 200 (Success) OR 400 (Bad Request)
deactivate AD

@enduml

