@startuml level_2

title Level 2 Diagram

hide empty members
'skinparam Linetype ortho

skinparam class {
    BackgroundColor<<valueObject>> #D6EAF8
    BackgroundColor<<root>> #FDEBD0
    BackgroundColor<<service>> #D1F2EB
    BackgroundColor #FEF9E7
    ArrowColor Black
}

skinparam package {
    BackgroundColor #EBF5FB
}

actor Patient as P
participant "MDR" as Backoffice

activate P
P -> Backoffice: Asks to Register as User
activate Backoffice
Backoffice --> P: Asks for data to register as User
deactivate Backoffice
P -> Backoffice: Sends data(email, password, phone number, name)
activate Backoffice
Backoffice --> Backoffice: Validates data and tries to create the User
Backoffice --> P: Returns Operation In/Sucess message
deactivate Backoffice

@enduml