@startuml level_2

title Level 2 Diagram

hide empty members
'skinparam Linetype ortho

skinparam class {
    BackgroundColor<<valueObject>> #D6EAF8
    BackgroundColor<<root>> #FDEBD0
    BackgroundColor<<service>> #D1F2EB
    BackgroundColor #FEF9E7
    ArrowColor Black
}

skinparam package {
    BackgroundColor #EBF5FB
}

actor Patient as P
participant "User Interface" as UI
participant "UserController" as C

activate P
P -> UI: Asks to Delete User Profile
activate UI
UI -> C: RequestDelete(token)
activate C
C -> C: Validates token and tries to process the request
C --> UI: Returns Operation Status Response Code
deactivate C
UI -> C: DeleteUser(token)
activate C
C -> C: Validates token and tries to delete the user
C --> UI: Returns Operation Status Response Code
deactivate C
UI --> P: Returns Operation In/Sucess message
deactivate UI

@enduml