@startuml US5.1.1 Level 2
'https://plantuml.com/sequence-diagram
skinparam handwritten false
skinparam monochrome false
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing true

actor Admin as AD
activate AD
AD -> UI: Create a user (username, email, role)
activate UI
UI -> MDR: createUser(username, email, role)
activate MDR
MDR --> MDR: Validate user's data
MDR --> UI: 200 (Success) OR 400 (Bad Request)
deactivate MDR
UI -> AD: 200 (Success) OR 400 (Bad Request)
deactivate UI

@enduml

