@startuml level_3_MDR

title Level 3 MDR Diagram for Removing Operation Request

hide empty members
'skinparam Linetype ortho

skinparam class {
    BackgroundColor<<valueObject>> #D6EAF8
    BackgroundColor<<root>> #FDEBD0
    BackgroundColor<<service>> #D1F2EB
    BackgroundColor #FEF9E7
    ArrowColor Black
}

skinparam package {
    BackgroundColor #EBF5FB
}

actor FE as FE
participant "OperationRequestController" as C
participant "OperationRequestService" as S
participant "OperationRequestRepository" as R
participant "LogRepository" as LR
participant "Log" as L
participant "Database" as DB

activate FE
FE -> C: Sends HTTP request to delete the Operation Request
activate C
C --> S: deleteOperationRequest(string operationRequestID)
activate S
S -> R: getByOperationRequestID(operationRequestID)
activate R
R -> DB: _objs.Where(x => x.operationRequestID == operationRequestID).FirstOrDefault()
activate DB
DB --> R: return var
deactivate DB
R --> S: return var
deactivate R
alt var is null
    S --> C: return null
else var is not null
    S -> R: Remove(request)
    activate R
    R -> DB: _objs.Remove(request)
    activate DB
    deactivate DB
    deactivate R
    S --> L: new Log(TypeOfAction.Delete, operationRequestID, "Operation Request Deleted")
    activate L
    L --> L: Log()
    deactivate L
    S --> LR: AddAsync(log)
    activate LR
    LR -> DB: _objs.AddAsync(log)
    activate DB
    deactivate DB
    deactivate LR
    S --> C: return request
    deactivate S
end
C --> FE: Returns Operation Status Response Code
deactivate C

@enduml