@startuml level_1

title Level 1 Diagram for Creating Staff

hide empty members

skinparam class {
    BackgroundColor<<valueObject>> #D6EAF8
    BackgroundColor<<root>> #FDEBD0
    BackgroundColor<<service>> #D1F2EB
    BackgroundColor #FEF9E7
    ArrowColor Black
}

skinparam package {
    BackgroundColor #EBF5FB
}

actor Admin as A
participant "Front-End" as FE
participant "Back-End" as BE

activate A
A -> FE: Request to create a Staff
activate FE
FE -> BE: Sends Staff's data (FirstName, LastName, FullName, Email, PhoneNumber, StaffType, SpecializationName)
activate BE
BE -> BE: Validates and creates Staff
BE --> FE: Returns Operation Status Code
deactivate BE
FE --> A: Returns Operation In/Success message
deactivate FE

@enduml