name: Angular CI

permissions:
  contents: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      working-directory: Angular-View

    - name: Build Angular project
      run: npm run build --if-present -- --output-path docs --base-href /LAPR5_3DC_G15/
      working-directory: Angular-View

    - name: Copy index.html to 404.html
      run: cp Angular-View/docs/index.html Angular-View/docs/404.html

    - name: Set up Git user
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      run: |
        npx angular-cli-ghpages --dir=Angular-View/docs --branch=gh-pages --no-silent
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Run Angular tests
      run: npm run test
      working-directory: Angular-View