name: Angular CI

permissions:
  contents: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      working-directory: Angular-View

    - name: Build Angular project
      run: npm run build --if-present -- --base-href /LAPR5_3DC_G15/
      working-directory: Angular-View

    - name: Copy server folder and prerendered-routes.json
      run: |
        mkdir -p Angular-View/dist/Angular-View/browser/server
        cp -r Angular-View/dist/Angular-View/server/* Angular-View/dist/Angular-View/browser/server/
        cp Angular-View/dist/Angular-View/prerendered-routes.json Angular-View/dist/Angular-View/browser/

    - name: Copy index.html to 404.html
      run: cp Angular-View/dist/Angular-View/browser/index.html Angular-View/dist/Angular-View/browser/404.html

    - name: Set up Git user
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - name: Pull latest changes from gh-pages
      run: |
        git clone https://github.com/vscosousa/LAPR5_3DC_G15.git
        cd LAPR5_3DC_G15
        git checkout gh-pages
        git pull origin gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      run: |
        npx angular-cli-ghpages --dir=Angular-View/dist/Angular-View/browser --branch=gh-pages --no-silent
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Run Angular tests
      run: npm run test
      working-directory: Angular-View