# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore
    
    - name: Install coverlet
      run: |
        dotnet tool install --global coverlet.console --version 1.7.0
        echo "${HOME}/.dotnet/tools" >> $GITHUB_PATH
    
    - name: Verify coverlet installation
      run: coverlet --version
    
    - name: Create coverage reports directory
      run: mkdir -p coverage_reports
    
    - name: Test with coverage
      run: dotnet test --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=./coverage_reports/coverage.opencover.xml

    - name: Check coverage report files
      run: ls -la coverage_reports
    
    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report-${{ github.run_id }}
        path: coverage_reports/coverage.opencover.xml
