name: .NET CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Run tests and generate coverage report
      run: dotnet test --no-build --collect:"XPlat Code Coverage"

    - name: Publish code coverage
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage
        path: '**/coverage.cobertura.xml'

    - name: Commit coverage report
      if: success()
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git checkout -b coverage-report
        mkdir -p coverage
        cp **/coverage.cobertura.xml coverage/
        git add coverage/coverage.cobertura.xml
        git commit -m "Add code coverage report"
        git push origin coverage-report