name: .NET CI

permissions:
  contents: write

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'
        dotnet-quality: 'ga'

    - name: Clean
      run: dotnet clean

    - name: Restore dependencies
      run: dotnet restore
      working-directory: Backoffice

    - name: Build
      run: dotnet build --no-restore
      working-directory: Backoffice

    - name: Run tests and generate coverage report
      run: dotnet test --no-build --collect:"XPlat Code Coverage" --results-directory ./TestResults
      continue-on-error: true
      working-directory: Backoffice

    - name: ReportGenerator
      uses: danielpalme/ReportGenerator-GitHub-Action@5.3.11
      with:
        reports: './Backoffice/TestResults/**/coverage.cobertura.xml'
        targetdir: 'coveragereport'
        reporttypes: 'HtmlInline;Cobertura;MarkdownSummaryGithub'
        sourcedirs: ''
        historydir: ''
        plugins: ''
        assemblyfilters: '+*'
        classfilters: '+*'
        filefilters: '+*'
        riskhotspotassemblyfilters: '+*'
        riskhotspotclassfilters: '+*'
        verbosity: 'Info'
        title: ''
        tag: '${{ github.run_number }}_${{ github.run_id }}'
        license: ''
        customSettings: ''
        toolpath: 'reportgeneratortool'

    - name: Upload coverage report artifact
      uses: actions/upload-artifact@v4
      with:
        name: CoverageReport
        path: coveragereport

    - name: Add comment to PR
      if: github.event_name == 'pull_request'
      run: gh pr comment ${{ github.event.pull_request.number }} --body-file coveragereport/SummaryGithub.md
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      working-directory: Backoffice

    - name: Publish coverage in build summary
      run: cat coveragereport/SummaryGithub.md >> $GITHUB_STEP_SUMMARY
      shell: bash
      working-directory: Backoffice