name: .NET Core CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'
        dotnet-quality: 'ga'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Run tests
      run: dotnet test --configuration Release --no-build --collect:"XPlat Code Coverage" --results-directory ./TestResults

    - name: Verify coverage report exists
      run: |
        if [ ! -f ./TestResults/coverage.cobertura.xml ]; then
          echo "Coverage report not found!"
          exit 1
        fi

    - name: Create coverage report directory
      run: mkdir -p coveragereport

    - name: ReportGenerator
      uses: danielpalme/ReportGenerator-GitHub-Action@5.3.11
      with:
        reports: './TestResults/coverage.cobertura.xml'
        targetdir: 'coveragereport'