name: .NET CI

permissions:
  contents: write

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Run tests and generate coverage report
      run: dotnet test --no-build --collect:"XPlat Code Coverage" --results-directory ./TestResults

    - name: Publish code coverage
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage
        path: './TestResults/**/coverage.cobertura.xml'

    - name: Set up Git user
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - name: Create coverage directory
      run: mkdir -p coverage

    - name: Copy coverage report to coverage directory
      run: cp ./TestResults/**/coverage.cobertura.xml coverage/

    - name: Add coverage report
      run: git add -f coverage/coverage.cobertura.xml

    - name: Commit and push changes
      env:
        PAT: ${{ secrets.PAT }}
      run: |
        git commit -m "Update code coverage report"
        git push https://x-access-token:${{ secrets.PAT }}@github.com/${{ github.repository }} HEAD:main