@startuml level_1
skinparam handwritten false
skinparam monochrome false
skinparam packageStyle rect
skinparam shadowing true
title 5.1.1 Level 1 Diagram

actor Admin as AD

activate AD
AD -> System: Ask to add new types of operations
activate System
System -> AD: Ask for types of operation data (name,requiredStaffBySpecialization,estimatedDuration)
AD -> System: Send types of operation data (name,requiredStaffBySpecialization,estimatedDuration)
System -> System: Validate data
System -> AD: Send confirmation message
deactivate System

@enduml